#ifndef __GLOBALS__H__
#define __GLOBALS__H__

#define __FULLY__OPTIMIZED__ 0
#include <stdint.h>
#include <stdlib.h>

#define true 1
#define false 0

#define BOARD_WIDTH 8 //tetris is 10
#define BOARD_HEIGHT 14 //tetris is 16
#define BOARD_SIZE BOARD_WIDTH * BOARD_HEIGHT

#define PIECE_WIDTH 4
#define PIECE_HEIGHT 4
#define PIECE_SIZE PIECE_WIDTH * PIECE_HEIGHT

#define DIGIT_BLOCK_SIZE 8
#define DIGIT_WIDTH 4
#define DIGIT_HEIGHT 7
#define DIGIT_SIDE_HEIGHT 2

#define BOARD_GRID_X_MIN BLOCK_SIZE + 2
#define BOARD_GRID_Y_MIN BLOCK_SIZE
#define BOARD_GRID_X_MAX BLOCK_SIZE * BOARD_WIDTH + BLOCK_SIZE + 2
#define BOARD_GRID_Y_MAX BLOCK_SIZE * BOARD_HEIGHT + BLOCK_SIZE

#define DIGIT_GRID_X_MAX 300
#define DIGIT_GRID_X_MIN DIGIT_GRID_X_MAX-DIGIT_WIDTH*DIGIT_BLOCK_SIZE*4
#define DIGIT_GRID_Y_MIN DIGIT_Y_ANCHOR
#define DIGIT_GRID_Y_MAX DIGIT_Y_ANCHOR+DIGIT_HEIGHT*DIGIT_BLOCK_SIZE

#endif
